### ISSUE TITLE
Extend MDR to include 3D image motion correction

### ISSUE THREAD

**Issue by JSousa-UoL** [QIB-Sheffield/mdreg#11]
There is no deadline for this, but it's a feature to add to this repository at some point. There 2 approaches we could take here:

1. Rename the `MDR.py` file to `MDR_2D.py` and create `MDR_3D.py`
2. Or edit the current `MDR.py` file to be "blind" and generic to dimensions. The strategy would involve using this type of indexing `[:]` and `[...]` in the shape variable instead of hard-coding if it's `shape[1]`, `shape[2]`, etc.

**Comment by KanishkaS** [comment]
this is now resolved
