### ISSUE TITLE
remove dbdicom source

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/mdreg#21]
since dbdicom is now a pipinstall package - can we remove source code from mdreg?

**Comment by JSousa-UoL** [comment]
I can do that. I will set the dbdicom version to be 0.0.5. If you wish to update this version in the future, you would have to change the version in `requirements.txt`. This is to avoid a potential risk where newer versions of dbdicom could have a different structure and therefore invalidate the `examples.py` file.
