### ISSUE TITLE
nan_to_num - replace by error handling

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/mdreg#30]
In _coregister (main.py) the np function nan_to_num is called to remove NaN values and infinities. This is dangerous because the data are manipulated tacitly and the NaN values and infinities may well be intentional - replacing NaN with actual numbers could have unintenden consequences without the caller being aware that this change was  made.

If Elastix can't handle NaN values then the solution is to stop execution and throw and exception to make the caller aware that the images need to be cleaned. To make this slightly more convenient you can add a keyword argument nan_to_num which is set to False by default, and does nothing in that case, but calles nan_to_num when it is set to True.

**Comment by KanishkaS** [comment]
Removed nan to num condition in the main script.
