### ISSUE TITLE
Optimisation of elastix parameters

### ISSUE THREAD

**Issue by kteh123** [QIB-Sheffield/mdreg#32]
Would be great to have extra information regarding parameter tuning of the elastix parameters. Maybe a link to the elastix documentation or some useful examples. These examples can be some common elastix parameters used to improve the model more or where a user can start if they want to improve their motion correction.

**Comment by KanishkaS** [comment]
Elastix model zoo repository link: https://github.com/SuperElastix/ElastixModelZoo/blob/master/models/default/Parameters_BSpline.txt

**Comment by KanishkaS** [comment]
elastix wiki: https://github.com/SuperElastix/elastix/wiki
